fix(server): alter-user, ignore errors
Prevent failure if password expiration is not set.
Example of error:
additional info: modify/delete: pwdAccountLockedTime: no such attribute

diff --git a/server/usr/local/bin/alter-user b/server/usr/local/bin/alter-user
--- a/server/usr/local/bin/alter-user
+++ b/server/usr/local/bin/alter-user
@@ -126,6 +126,25 @@ fi
         }'
     fi
 
+    # Change mail attribute
+    if [ -n "${mail}" ]; then
+        printf '\n' # do not conflict with previous ldap commands
+        printf 'dn: uid=%s,ou=People,%s\n' "${user}" "${LDAP_SUFFIX:?}"
+        printf 'changetype: modify\n'
+        printf 'replace: mail\n'
+        printf 'mail: %s\n' "${mail}"
+    fi
+
+) | ldapmodify -Q
+
+if [ $? != 0 ]; then
+    errors=$((errors + 1))
+    echo "[ERROR] Alter user ${user} failed" 1>&2
+fi
+
+# Execute lock/unlock operations in a separate ldapmodify command because
+# they can fail without preventing other operations to succeed
+(
     # Lock user
     if [ "${lflag}" = 1 ]; then
         printf '\n' # do not conflict with previous ldap commands
@@ -143,21 +162,7 @@ fi
         printf 'delete: pwdAccountLockedTime\n'
     fi
 
-    # Change mail attribute
-    if [ -n "${mail}" ]; then
-        printf '\n' # do not conflict with previous ldap commands
-        printf 'dn: uid=%s,ou=People,%s\n' "${user}" "${LDAP_SUFFIX:?}"
-        printf 'changetype: modify\n'
-        printf 'replace: mail\n'
-        printf 'mail: %s\n' "${mail}"
-    fi
-
-) | ldapmodify -Q
-
-if [ $? != 0 ]; then
-    errors=$((errors + 1))
-    echo "[ERROR] Alter user ${user} failed" 1>&2
-fi
+) | ldapmodify -Q -c
 
 if [ "${errors}" != 0 ]; then
     exit 1
